# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2

environment:
  BASH_ENV: "~/.bashrc"

references:
  common: &common
    environment:
      BASH_ENV: "~/.bashrc"
    steps: &steps
      - checkout
      - run: apt-get update && apt-get -y install expect
      - run: expect -c "spawn ssh-add - <<< "${SSH_KEY}" expect -re \"Enter passphrase for (stdin):\"; send \"n\";"
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: git config --global user.email "tothimre@gmail.com" && git config --global user.name "Imre Toth"
      - run: ./bin/node-modules-cache-key.js > ./npm-minor-hash
      - restore_cache:
          keys:
            - deps-{{ checksum "npm-minor-hash" }}
      - run: ls -lah
      - run: ./bin/install.sh
      - run: npm test
      - run: ./bin/cache-packages-update.js
      - save_cache:
          key: deps-{{ checksum "npm-minor-hash" }}
          paths:
            #beginning package template
            - packages/container/node_modules
            - packages/cowlog/node_modules
            - packages/directory-fixture-provider/node_modules
            - packages/dsl-framework/node_modules
            - packages/dsl-framework/examples/auto-publish/parenting/node_modules
            - packages/generic-text-linker/node_modules
            - packages/refresh-me/node_modules
            - packages/require-a-lot/node_modules
            - node_modules
            #end package template
  #somehow redundant pieces shall be referenced.
  common_steps_upload: &common_steps_upload
    environment:
      BASH_ENV: "~/.bashrc"
    steps:
      - checkout
      - run: apt-get update && apt-get -y install expect
      - run: echo "${HOME}/bin/cc-test-reporter"
      - run: mkdir -p bin; curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > "/tmp/tr" && chmod +x "/tmp/tr"
      - run: expect -c "spawn ssh-add - <<< "${SSH_KEY}" expect -re \"Enter passphrase for (stdin):\"; send \"n\";"
      - run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run: git config --global user.email "tothimre@gmail.com" && git config --global user.name "Imre Toth"
      - run: ./bin/node-modules-cache-key.js > ./npm-hash
      - restore_cache:
          keys:
            - deps-{{ checksum "npm-hash" }}
      - run: ls -lah
      - run: ./bin/install.sh
      - run: /tmp/tr before-build
      - run: npm run test
      - run: /tmp/tr after-build --exit-code $?
      - save_cache:
          key: deps-{{ checksum "npm-hash" }}
          paths:
            #beginning package template
            - packages/container/node_modules
            - packages/cowlog/node_modules
            - packages/directory-fixture-provider/node_modules
            - packages/dsl-framework/node_modules
            - packages/dsl-framework/examples/auto-publish/parenting/node_modules
            - packages/generic-text-linker/node_modules
            - packages/refresh-me/node_modules
            - packages/require-a-lot/node_modules
            - node_modules
            #end package template
      - store_artifacts:
          path: coverage
          destination: prefix
      - store_test_results:
          path: coverage/lcov-report/
      - run: /tmp/tr after-build --coverage-input-type lcov --exit-code $? ./coverage/lcov.info
      - run: bin/github.js

jobs:

  # node12:
  #   docker:
  #     - image: node:12
  #   <<: [ *common ]

  node14:
    docker:
      - image: node:14
    <<: [ *common ]

  # node16:
  #   docker:
  #     - image: node:16
  #   <<: [ *common ]

  # node18:
  #   docker:
  #     - image: node:18
  #   <<: [ *common_steps_upload ]

workflows:
  version: 2
  build:
    jobs:
      - node14
      # - node16
      # - node18
