name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted]
    container:
      image: node:current-buster-slim
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: bin/install.sh
    - run: npm run test
