name: CI
on: [push]
jobs:
  install-test-flow:
    runs-on: [self-hosted]
    container:
      image: node:current-buster-slim
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Check out repository code
      uses: actions/checkout@v3
    
    - run: |
        apt-get update && apt-get -y install git tree && tree &&
        git config --global user.email "you@example.com" && git config --global user.name "Your Name"
  
    - run: bin/install.sh

    - name: testing
      run: npm run test          
