name: CI

on: [push]

jobs:
  install-test-flow:
    runs-on: [self-hosted]
    container:
      image: node:current-buster-slim
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    # - uses: actions/github-script@v6
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: |
        node -v && npm i
    - run: |
        apt-get update && apt-get -y install git &&
        git config --global user.email "you@example.com" && git config --global user.name "Your Name"

  # publish-dsl-framework:
  #   runs-on: [self-hosted]
  #   container:
  #     image: node:current-buster-slim
  #   steps:
  #   - run : |
  #       cd packages/dsl-framework && echo happy
  #   rules:
  #     - changes:
  #       - packages/dsl-framework/package*.json
  #       - packages/dsl-framework/src/*
  #       - packages/dsl-framework/src/**/*

