name: CI
on: [push]
jobs:
  install-test-flow:
    runs-on: [self-hosted]
    container:
      image: node:current-buster-slim
    steps:
    - uses: actions/checkout@v3
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.OS }}-npm-cache-
    - uses: actions/setup-node@v3
      with:
        node-version: 14

    - run: |
        apt-get update && apt-get -y install git tree && tree &&
        git config --global user.email "you@example.com" && git config --global user.name "Your Name"

    - uses: nick-fields/retry@v2
      with:
        timeout_seconds: 15
        max_attempts: 3
        command: npm install && npx lerna bootstrap
        on_retry_command: npx lerna clean && npm install && npx lerna bootstrap

    - name: testing
      run: npm run test
